project 'CMUtilities.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CMUtilities' do
  platform :ios, '12.0'
  use_frameworks!
  
  pod 'RxSwift', '~> 4.5.0'
  pod 'RxCocoa', '~> 4.5.0'
  pod 'ReSwift', '~> 4.1.1'
  pod 'PointFree-Validated', '~> 0.2.0'
  
  target 'CMUtilitiesTests' do
    inherit! :search_paths
  end

end
